language: ruby
rvm:
  - ruby-head
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-head
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
  - rbx-18mode
  - ree
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
notifications:
  irc: 'irc.freenode.org#ponder'
